// SPDX-License-Identifier: Apache-2.0
package com.m3.rewrite.index;

import com.m3.indexdb.M3IndexDbSemanticNode;
import org.openrewrite.Column;
import org.openrewrite.DataTable;
import org.openrewrite.Recipe;

/** Canonical child-first semantic hashes generated by M3IndexDB after OpenRewrite fan-in. */
public final class M3SemanticHashTable extends DataTable<M3SemanticHashTable.Row> {
    public M3SemanticHashTable(Recipe recipe) {
        super(
                recipe,
                "M3 canonical semantic hashes",
                "Canonical ATOM-through-REPOSITORY structural, logic and SimHash identities after child-first fan-in.");
    }

    public static final class Row {
        @Column(displayName = "Node ID", description = "Stable semantic node identity.")
        private final String nodeId;
        @Column(displayName = "Kind", description = "ATOM/FIELD/METHOD/FILE/type/docs/package/module/library/project/repository.")
        private final String kind;
        @Column(displayName = "Semantic key", description = "Stable semantic address.")
        private final String semanticKey;
        @Column(displayName = "Source path", description = "Direct source owner when present.")
        private final String sourcePath;
        @Column(displayName = "Pattern role", description = "First-class M3/IOP participant role.")
        private final String patternRole;
        @Column(displayName = "Exact SHA-256", description = "Exact content identity.")
        private final String exactSha256;
        @Column(displayName = "Structural SHA-256", description = "Normalized structural identity.")
        private final String structuralSha256;
        @Column(displayName = "Logic SHA-256", description = "Normalized logic/composition identity.")
        private final String logicSha256;
        @Column(displayName = "Structural hash64", description = "Compact structural lookup signal.")
        private final String structuralHash64;
        @Column(displayName = "Logic hash64", description = "Compact normalized logic lookup signal.")
        private final String logicHash64;
        @Column(displayName = "SimHash64", description = "Candidate-only locality-sensitive semantic similarity signal.")
        private final String simHash64;
        @Column(displayName = "Child count", description = "Canonical direct child count.")
        private final int childCount;
        @Column(displayName = "Parent count", description = "Canonical direct parent count.")
        private final int parentCount;
        @Column(displayName = "Normalized composition", description = "Canonical normalized semantic composition.")
        private final String normalizedComposition;

        public Row(M3IndexDbSemanticNode node, int childCount, int parentCount) {
            this.nodeId = node.nodeId();
            this.kind = node.kind().name();
            this.semanticKey = node.semanticKey();
            this.sourcePath = node.sourcePath();
            this.patternRole = node.patternRole();
            this.exactSha256 = node.fingerprint().exactSha256();
            this.structuralSha256 = node.fingerprint().structuralSha256();
            this.logicSha256 = node.fingerprint().logicSha256();
            this.structuralHash64 = node.fingerprint().structuralHash64Hex();
            this.logicHash64 = node.fingerprint().logicHash64Hex();
            this.simHash64 = node.fingerprint().simHash64Hex();
            this.childCount = childCount;
            this.parentCount = parentCount;
            this.normalizedComposition = node.fingerprint().normalizedComposition();
        }

        public String nodeId() { return nodeId; }
        public String kind() { return kind; }
        public String semanticKey() { return semanticKey; }
        public String sourcePath() { return sourcePath; }
        public String patternRole() { return patternRole; }
        public String exactSha256() { return exactSha256; }
        public String structuralSha256() { return structuralSha256; }
        public String logicSha256() { return logicSha256; }
        public String structuralHash64() { return structuralHash64; }
        public String logicHash64() { return logicHash64; }
        public String simHash64() { return simHash64; }
        public int childCount() { return childCount; }
        public int parentCount() { return parentCount; }
        public String normalizedComposition() { return normalizedComposition; }
    }
}
