// SPDX-License-Identifier: Apache-2.0
package com.m3.indexdb;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** ContractProbe for strict V1 text and payload-relative allocation bounds. */
final class CodecTest {
    @TempDir Path home;

    @Test
    void malformedUtf8NeverBecomesReplacementMetadata() {
        List<byte[]> invalid = List.of(
                new byte[] {(byte) 0xff},
                new byte[] {(byte) 0x80},
                new byte[] {(byte) 0xc0, (byte) 0xaf},
                new byte[] {(byte) 0xe0, (byte) 0x80, (byte) 0xaf},
                new byte[] {(byte) 0xed, (byte) 0xa0, (byte) 0x80},
                new byte[] {(byte) 0xf4, (byte) 0x90, (byte) 0x80, (byte) 0x80},
                new byte[] {(byte) 0xf5, (byte) 0x80, (byte) 0x80, (byte) 0x80});
        for (byte[] sequence : invalid) {
            byte[] bytes = CodecProbe.sample("src/ZZZZ.java").encode();
            int at = CodecProbe.locate(bytes, "src/ZZZZ.java".getBytes(StandardCharsets.UTF_8));
            System.arraycopy(sequence, 0, bytes, at, sequence.length);
            byte[] saved = bytes.clone();
            var failure = assertThrows(IllegalArgumentException.class,
                    () -> M3IndexDbSemanticIndex.decode(bytes));
            assertInstanceOf(CharacterCodingException.class, failure.getCause());
            assertArrayEquals(saved, bytes);
        }
    }

    @Test
    void truncatedMultibyteSequenceAtStringBoundaryIsRefused() {
        byte[] bytes = CodecProbe.sample("src/ZZZZ.java").encode();
        byte[] marker = "src/ZZZZ.java".getBytes(StandardCharsets.UTF_8);
        bytes[CodecProbe.locate(bytes, marker) + marker.length - 1] = (byte) 0xc2;
        assertThrows(IllegalArgumentException.class, () -> M3IndexDbSemanticIndex.decode(bytes));
    }

    @Test
    void unpairedSurrogatesAreRefusedRatherThanLossilyEncoded() {
        for (String text : List.of("\ud800", "\udc00", "A\ud800B", "\ud800\ud800", "\udc00\ud800")) {
            var failure = assertThrows(IllegalArgumentException.class,
                    () -> CodecProbe.sample(text).encode());
            assertInstanceOf(CharacterCodingException.class, failure.getCause());
        }
    }

    @Test
    void validUnicodeAndLiteralReplacementCharacterRoundTripExactly() {
        for (String text : List.of("", "ASCII", "é/漢字", "\ufffd", "\ud83d\ude00",
                "e\u0301", "\u00e9", "\ufeff", "  src\\Path.java  ")) {
            var index = CodecProbe.sample(text);
            byte[] bytes = index.encode();
            var decoded = M3IndexDbSemanticIndex.decode(bytes);
            assertEquals(index.nodes(), decoded.nodes());
            assertArrayEquals(bytes, decoded.encode());
        }
        assertFalse(Arrays.equals(CodecProbe.sample("e\u0301").encode(),
                CodecProbe.sample("\u00e9").encode()), "No Unicode normalization");
    }

    @Test
    void generatedValidTextRetainsSemanticIdentityAndEncoding() throws Exception {
        MessageDigest corpus = MessageDigest.getInstance("SHA-256");
        Random random = new Random(672493L);
        for (int n = 0; n < 128; n++) {
            StringBuilder text = new StringBuilder("src/");
            for (int i = 0; i < n; i++) {
                int codePoint;
                do {
                    codePoint = random.nextInt(0x110000);
                } while (codePoint >= 0xd800 && codePoint <= 0xdfff);
                text.appendCodePoint(codePoint);
            }
            text.append(".java");
            var before = CodecProbe.sample(text.toString());
            byte[] bytes = before.encode();
            var after = M3IndexDbSemanticIndex.decode(bytes);
            assertEquals(before.nodes(), after.nodes());
            assertArrayEquals(bytes, after.encode());
            corpus.update(ByteBuffer.allocate(8).putInt(n).putInt(bytes.length).array());
            corpus.update(bytes);
        }
        // Generated by original codec Git blob 316c3824409a29a0acc0d15fccca23132b317d36.
        assertEquals("d972971c21142f82252f5cb912f7c17fee34af248767df251175228aa402c594",
                HexFormat.of().formatHex(corpus.digest()));
    }

    @Test
    void fabricatedCountsAreRejectedInSmallHeapProcesses() throws Exception {
        for (int position : List.of(12, 16, 20)) {
            Path log = home.resolve("count-" + position + ".log");
            String java = Path.of(System.getProperty("java.home"), "bin", "java").toString();
            String classpath = System.getProperty("surefire.test.class.path",
                    System.getProperty("java.class.path"));
            Process child = new ProcessBuilder(java, "-Xmx32m", "-cp", classpath,
                    CodecProbe.class.getName(), "count", Integer.toString(position))
                    .redirectErrorStream(true).redirectOutput(log.toFile()).start();
            try {
                assertTrue(child.waitFor(20, TimeUnit.SECONDS), "bounded validation timeout");
                String output = Files.readString(log);
                assertEquals(0, child.exitValue(), output);
                assertEquals("COUNT_REJECTED", output.strip());
            } finally {
                if (child.isAlive()) child.destroyForcibly().waitFor();
            }
        }
    }

    @Test
    void fixedRecordsMustFitBeforeAnyStringCapacityIsAllocated() {
        for (int position : List.of(12, 16, 20)) {
            byte[] bytes = header(0, 0, 0);
            ByteBuffer.wrap(bytes).putInt(position, 50_000_000);
            assertThrows(IllegalArgumentException.class, () -> M3IndexDbSemanticIndex.decode(bytes));
        }
        assertThrows(IllegalArgumentException.class,
                () -> M3IndexDbSemanticIndex.decode(header(50_000_000, 50_000_000, 50_000_000)));
        assertArrayEquals(header(0, 0, 0),
                M3IndexDbSemanticIndex.decode(header(0, 0, 0)).encode());
    }

    @Test
    void stringLengthCannotConsumeReservedNodesOrOtherPrefixes() {
        byte[] node = Arrays.copyOf(header(1, 1, 0), 24 + 4 + 173);
        ByteBuffer.wrap(node).putInt(24, 173);
        var failure = assertThrows(IllegalArgumentException.class,
                () -> M3IndexDbSemanticIndex.decode(node));
        assertTrue(failure.getMessage().contains("exceed payload"));
        byte[] strings = Arrays.copyOf(header(2, 0, 0), 32);
        ByteBuffer.wrap(strings).putInt(24, 4);
        assertThrows(IllegalArgumentException.class, () -> M3IndexDbSemanticIndex.decode(strings));
    }

    @Test
    void encodingUsesTheDecodersExistingByteLimit() {
        var overChars = CodecProbe.sample("x".repeat(16 * 1024 * 1024 + 1));
        assertThrows(IllegalArgumentException.class, overChars::encode);
        var overBytes = CodecProbe.sample("é".repeat(8 * 1024 * 1024 + 1));
        assertThrows(IllegalArgumentException.class, overBytes::encode);
    }

    @Test
    void rejectedEncodingDoesNotPublishOrReplaceDatabaseArtifact() throws Exception {
        byte[] before;
        try (M3IndexDB db = M3IndexDB.open(home)) {
            db.putSemanticIndex("snapshot", CodecProbe.sample("src/valid.java"));
            before = db.requireArtifact("snapshot").payload();
            long bytes = db.blobBytes();
            assertThrows(IllegalArgumentException.class,
                    () -> db.putSemanticIndex("snapshot", CodecProbe.sample("\ud800")));
            assertThrows(IllegalArgumentException.class,
                    () -> db.putSemanticIndex("new", CodecProbe.sample("\udc00")));
            assertFalse(db.containsArtifact("new"));
            assertEquals(bytes, db.blobBytes());
            assertArrayEquals(before, db.requireArtifact("snapshot").payload());
        }
        try (M3IndexDB reopened = M3IndexDB.open(home)) {
            assertArrayEquals(before, reopened.requireSemanticIndex("snapshot").encode());
        }
    }

    @Test
    void storedMalformedPayloadRetainsDatabaseIOExceptionBoundary() throws Exception {
        byte[] bytes = CodecProbe.sample("src/ZZZZ.java").encode();
        bytes[CodecProbe.locate(bytes, "src/ZZZZ.java".getBytes(StandardCharsets.UTF_8))] = (byte) 0xff;
        try (M3IndexDB db = M3IndexDB.open(home)) {
            db.putArtifact("bad", M3IndexDbSemanticIndex.ARTIFACT_KIND,
                    M3IndexDbSemanticIndex.FORMAT_VERSION, bytes);
        }
        try (M3IndexDB reopened = M3IndexDB.open(home)) {
            var failure = assertThrows(IOException.class, () -> reopened.requireSemanticIndex("bad"));
            var invalid = assertInstanceOf(IllegalArgumentException.class, failure.getCause());
            assertInstanceOf(CharacterCodingException.class, invalid.getCause());
            assertArrayEquals(bytes, reopened.requireArtifact("bad").payload());
        }
    }

    private static byte[] header(int strings, int nodes, int edges) {
        return ByteBuffer.allocate(24).putLong(0x4d3349444253454dL)
                .putInt(1).putInt(strings).putInt(nodes).putInt(edges).array();
    }
}
