// SPDX-License-Identifier: Apache-2.0
package com.m3.rewrite.backport;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.IOException;
import java.io.StringReader;
import java.nio.ByteBuffer;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.List;
import java.util.Properties;
import java.util.Set;
import org.openrewrite.ExecutionContext;
import org.openrewrite.Option;
import org.openrewrite.Recipe;
import org.openrewrite.Tree;
import org.openrewrite.TreeVisitor;

/**
 * Fail-closed receiver guard for content-addressed Synexia handoff packets.
 *
 * <p>The guard is intentionally mutation-free. It validates the provenance packet generated by
 * Synexia before the following hash-pinned Java/text snapshot recipes are allowed to run. Target
 * promotion remains outside this recipe and still requires M3JDK21 build, jtreg and runtime proof.
 * </p>
 */
public final class M3SynexiaHandoffGuardRecipe extends Recipe {
    private static final String VERSION = "SYNEXIA_M3_HANDOFF_V1";
    private static final String RESOURCE_ROOT =
            "/com/m3/rewrite/backport/synexia-bridge/";

    @Option(
            displayName = "Synexia crate name",
            description = "Content-addressed Synexia handoff crate to validate.",
            example = "synexia-string-precompute-v1")
    private final String crateName;

    @JsonCreator
    public M3SynexiaHandoffGuardRecipe(@JsonProperty("crateName") String crateName) {
        if (crateName == null
                || !crateName.matches("synexia-[a-z0-9][a-z0-9-]{0,63}")) {
            throw new IllegalArgumentException("invalid Synexia handoff crate");
        }
        this.crateName = crateName;
    }

    public String getCrateName() {
        return crateName;
    }

    @Override
    public String getDisplayName() {
        return "Validate Synexia content-addressed handoff";
    }

    @Override
    public String getDescription() {
        return "Validates Synexia provenance, hashes and Apache-2.0 M3-owned transfer boundaries before target mutation.";
    }

    @Override
    public Set<String> getTags() {
        return Set.of(
                "m3",
                "synexia",
                "jdk21",
                "openrewrite",
                "provenance",
                "hash-pinned",
                "fail-closed",
                "candidate-only");
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        validatePacket();
        return new TreeVisitor<Tree, ExecutionContext>() {};
    }

    private void validatePacket() {
        String root = RESOURCE_ROOT + crateName + "/";
        String packet = resource(root + "packet.tsv");
        Properties properties = properties(resource(root + "bridge.properties"));

        requireEquals(VERSION, properties.getProperty("version"), "version");
        requireEquals(crateName, properties.getProperty("crate"), "crate");
        requireSha(properties.getProperty("packetRoot"), "packetRoot");
        requireEquals(sha256(packet), properties.getProperty("packetRoot"), "packetRoot");

        List<String> lines = packet.lines().filter(line -> !line.isBlank()).toList();
        if (lines.size() < 4 || !("# " + VERSION).equals(lines.get(0))) {
            throw new IllegalStateException("invalid Synexia handoff packet header");
        }
        requireEquals("@crate\t" + crateName, lines.get(1), "packet crate");

        String sourceRevision = properties.getProperty("sourceRevision");
        if (sourceRevision == null || !sourceRevision.matches("[0-9a-f]{40}")) {
            throw new IllegalStateException("invalid Synexia source revision");
        }
        requireEquals("@source-revision\t" + sourceRevision, lines.get(2), "source revision");

        int rows = 0;
        Set<String> targets = new HashSet<>();
        for (int index = 3; index < lines.size(); index++) {
            String[] cells = lines.get(index).split("\t", -1);
            if (cells.length != 13 || !"ROW".equals(cells[0])) {
                throw new IllegalStateException("invalid Synexia handoff row");
            }
            if (!Set.of("JAVA", "TEXT", "NATIVE").contains(cells[1])) {
                throw new IllegalStateException("invalid Synexia handoff kind");
            }
            requireSha(cells[4], "sourceSha");
            String target = relative(cells[5]);
            if (!targets.add(target)) {
                throw new IllegalStateException("duplicate Synexia handoff target: " + target);
            }
            if (!"ABSENT".equals(cells[6])) {
                requireSha(cells[6], "targetBefore");
            }
            requireSha(cells[7], "targetAfter");
            if (!cells[8].matches("[A-Za-z0-9_.-]+")) {
                throw new IllegalStateException("invalid Synexia payload leaf");
            }
            if (m3OwnedTargetPath(target) && !"Apache-2.0".equals(cells[9])) {
                throw new IllegalStateException(
                        "M3-owned Synexia target requires Apache-2.0 direct bytes: " + target);
            }
            requireSha(cells[11], "contractRoot");
            requireSha(cells[12], "gateRoot");
            rows++;
        }

        int expectedRows;
        try {
            expectedRows = Integer.parseInt(properties.getProperty("rows"));
            Long.parseLong(properties.getProperty("payloadBytes"));
        } catch (RuntimeException invalid) {
            throw new IllegalStateException("invalid Synexia handoff counters", invalid);
        }
        if (rows < 1 || rows != expectedRows) {
            throw new IllegalStateException("Synexia handoff row count mismatch");
        }
    }

    static boolean m3OwnedTargetPath(String value) {
        return value != null && (value.startsWith("m3/") || value.startsWith(".m3/"));
    }

    private static String relative(String value) {
        if (value == null
                || value.isBlank()
                || value.startsWith("/")
                || value.matches("^[A-Za-z]:/.*")
                || value.indexOf('\\\\') >= 0
                || value.length() > 4096
                || value.chars().anyMatch(Character::isISOControl)) {
            throw new IllegalStateException("invalid Synexia target path");
        }
        for (String part : value.split("/", -1)) {
            if (part.isEmpty()
                    || ".".equals(part)
                    || "..".equals(part)
                    || ".git".equalsIgnoreCase(part)) {
                throw new IllegalStateException("noncanonical Synexia target path");
            }
        }
        return value;
    }

    private static Properties properties(String text) {
        Properties properties = new Properties();
        try {
            properties.load(new StringReader(text));
        } catch (IOException impossible) {
            throw new IllegalStateException("cannot parse Synexia bridge properties", impossible);
        }
        return properties;
    }

    private static void requireEquals(String expected, String actual, String field) {
        if (!expected.equals(actual)) {
            throw new IllegalStateException("invalid Synexia " + field);
        }
    }

    private static void requireSha(String value, String field) {
        if (value == null || !value.matches("[0-9a-f]{64}")) {
            throw new IllegalStateException("invalid Synexia " + field);
        }
    }

    private static String resource(String name) {
        try (var stream = M3SynexiaHandoffGuardRecipe.class.getResourceAsStream(name)) {
            if (stream == null) {
                throw new IllegalStateException("missing Synexia handoff resource: " + name);
            }
            return StandardCharsets.UTF_8
                    .newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(stream.readAllBytes()))
                    .toString();
        } catch (IOException failure) {
            throw new IllegalStateException("cannot read Synexia handoff resource", failure);
        }
    }

    private static String sha256(String value) {
        try {
            return HexFormat.of().formatHex(
                    MessageDigest.getInstance("SHA-256")
                            .digest(value.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException impossible) {
            throw new ExceptionInInitializerError(impossible);
        }
    }
}
